### ISSUE TITLE
Errno 2, No such file or directory

### ISSUE THREAD

**Issue by dlarrain** [riyas-org/nrf24pihub#1]
Im having the following problem after install everything

$ sudo python raspberryfriend.py 
Traceback (most recent call last):
File "raspberryfriend.py", line 13, in 
radio.begin(0,0,25,18) #set gpio 25 as CE pin
File "/home/pi/nrf24pihub/nrf24.py", line 369, in begin
self.spidev.open(major, minor)
IOError: [Errno 2] No such file or directory

Do you know what could it be?

**Comment by riyas-org** [comment]
make sure spi is working on your pi. Spi has problems with latest versions of raspbian. See the user comments in my post http://blog.riyas.org/2014/08/raspberry-pi-as-nrf24l01-base-station-internet-connected-wireless.html
